version: '3.8'

# NOTES:
# for use of arg, env etc: https://vsupalov.com/docker-arg-env-variable-guide/
# a empty data directory must exist with user / group equal to hostuser (1000:1000)
# the site must be placed into www/html
# a directory www/edocman must exist

services:
  app:
    hostname: app.local
    container_name: app
    build:
      context: app/.
#      args:
#        adminid: henk
#        adminpw: helhond
#        userid: sanssouci
#        userpw: zuidschermer
#        loglevel: debug # debug, trace8, crit
#        uiduser: 1000
#        giduser: 1000
    ports:
    - "80:9000"
#    volumes:
#    - ./www:/var/www
#    environment:
#      XDEBUG_CONFIG: "client_host=192.168.2.10"
#      XDEBUG_MODE: "debug,develop"
#    dns: 0.0.0.0 # no internet access
    
